"""add places api, and unique constraints to country and city

Revision ID: 26d0564fa91a
Revises: 30308603793e
Create Date: 2026-10-09 02:37:16.550570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '26d0564fa91a'
down_revision: Union[str, Sequence[str], None] = '30308603793e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('place',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city', sa.Uuid(), nullable=False),
    sa.Column('country', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['city'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'latitude', 'longitude', 'city', 'country', name='Unique place constraint')
  )
  op.create_index(op.f('ix_place_city'), 'place', ['city'], unique=False)
  op.create_index(op.f('ix_place_country'), 'place', ['country'], unique=False)
  op.create_table('placesuservisitedlink',
    sa.Column('places_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['places_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('places_id', 'user_id')
  )
  op.create_index(op.f('ix_city_country'), 'city', ['country'], unique=False)
  op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=True)
  op.drop_constraint(op.f('country_name_key'), 'country', type_='unique')
  op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=True)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_country_name'), table_name='country')
  op.create_unique_constraint(op.f('country_name_key'), 'country', ['name'], postgresql_nulls_not_distinct=False)
  op.drop_index(op.f('ix_city_name'), table_name='city')
  op.drop_index(op.f('ix_city_country'), table_name='city')
  op.drop_table('placesuservisitedlink')
  op.drop_index(op.f('ix_place_country'), table_name='place')
  op.drop_index(op.f('ix_place_city'), table_name='place')
  op.drop_table('place')
  # ### end Alembic commands ###
