"""remove route constraint

Revision ID: 30308603793e
Revises: 370513e21407
Create Date: 2026-10-01 00:44:28.678448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30308603793e'
down_revision: Union[str, Sequence[str], None] = '370513e21407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(op.f('Unique route constraint'), 'route', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_unique_constraint(op.f('Unique route constraint'), 'route', ['start', 'end'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
