"""Add user stats table

Revision ID: 370513e21407
Revises: 379a285392a9
Create Date: 2026-09-30 23:34:01.924449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370513e21407'
down_revision: Union[str, Sequence[str], None] = '379a285392a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('userstats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('no_of_trips', sa.Integer(), nullable=False),
    sa.Column('distance_covered', sa.Float(), nullable=False),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('average_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
  )
  op.create_index(op.f('ix_userstats_user_id'), 'userstats', ['user_id'], unique=True)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_userstats_user_id'), table_name='userstats')
  op.drop_table('userstats')
  # ### end Alembic commands ###
