"""Added account table

Revision ID: 379a285392a9
Revises: 2f39e40ae739
Create Date: 2026-09-30 23:27:20.497802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379a285392a9'
down_revision: Union[str, Sequence[str], None] = '2f39e40ae739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('tripstore',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('stop_latitude', sa.Float(), nullable=False),
    sa.Column('stop_longitude', sa.Float(), nullable=False),
    sa.Column('country', sa.Uuid(), nullable=True),
    sa.Column('city', sa.Uuid(), nullable=True),
    sa.Column('trip_status', sa.Enum('PENDING', 'COMPLETED', name='tripstatus'), nullable=False),
    sa.Column('carried_out_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country'], ['country.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
  )
  op.create_index(op.f('ix_tripstore_city'), 'tripstore', ['city'], unique=False)
  op.create_index(op.f('ix_tripstore_country'), 'tripstore', ['country'], unique=False)
  op.create_index(op.f('ix_tripstore_user_id'), 'tripstore', ['user_id'], unique=False)
  op.create_unique_constraint(None, 'country', ['name'])
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  # WARNING: constraint name is None; this directive will fail as
  # rendered.  Add a name, or use a naming convention; see
  # https://alembic.sqlalchemy.org/en/latest/naming.html
  op.drop_constraint(None, 'country', type_='unique')
  op.drop_index(op.f('ix_tripstore_user_id'), table_name='tripstore')
  op.drop_index(op.f('ix_tripstore_country'), table_name='tripstore')
  op.drop_index(op.f('ix_tripstore_city'), table_name='tripstore')
  op.drop_table('tripstore')
  # ### end Alembic commands ###
