"""create tables

Revision ID: 88923ac109d9
Revises: 95d80562c02f
Create Date: 2026-09-28 10:57:59.446666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88923ac109d9'
down_revision: Union[str, Sequence[str], None] = '95d80562c02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('country',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
  op.create_table('transportmode',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
  op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
  op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
  op.create_table('city',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
  op.create_table('records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'DELETED', 'EDITED', 'DISABLED', name='adminaction'), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
  op.create_table('stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sa.Uuid(), nullable=False),
    sa.Column('country', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['city'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude', 'longitude', 'city', 'country', name='Unique location constraint'),
    sa.UniqueConstraint('name')
    )
  op.create_table('route',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('start', sa.Uuid(), nullable=False),
    sa.Column('end', sa.Uuid(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['end'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['start'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start', 'end', name='Unique route constraint')
    )
  op.create_table('transportmoderoutelink',
    sa.Column('transport_mode_id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['transport_mode_id'], ['transportmode.id'], ),
    sa.PrimaryKeyConstraint('transport_mode_id', 'route_id')
    )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('transportmoderoutelink')
  op.drop_table('route')
  op.drop_table('stops')
  op.drop_table('records')
  op.drop_table('city')
  op.drop_index(op.f('ix_user_email'), table_name='user')
  op.drop_table('user')
  op.drop_table('transportmode')
  op.drop_table('country')
  # ### end Alembic commands ###
