"""correct wrong name

Revision ID: b4f0768e46c4
Revises: 26d0564fa91a
Create Date: 2026-10-09 18:07:43.604160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b4f0768e46c4'
down_revision: Union[str, Sequence[str], None] = '26d0564fa91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('placetype',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
  op.create_index(op.f('ix_placetype_name'), 'placetype', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_placetype_name'), table_name='placetype')
  op.drop_table('placetype')
    # ### end Alembic commands ###
